apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  name: ai-ro
  namespace: ai-ns
  labels:
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/instance: "{{ .Release.Name }}"
  annotations:
    meta.helm.sh/release-name: "{{ .Release.Name }}"
    meta.helm.sh/release-namespace: "{{ .Release.Namespace }}"
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: ai-app
  template:
    metadata:
      labels:
        app: ai-app
    spec:
      containers:
        - name: ai-bluecon
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          ports:
            - containerPort: 8080
          readinessProbe:
            httpGet:
              path: /
              port: 8080
            initialDelaySeconds: 5
            periodSeconds: 5
  strategy:
    canary:
      canaryService: ai-svc-canary
      stableService: ai-svc-stable
      steps:
        - setWeight: 25
        - pause:
            duration: 30s
        - setWeight: 50
        - pause:
            duration: 30s
        - setWeight: 75
        - pause:
            duration: 30s
        - setWeight: 100