# This is the name of your workflow
name: Update Kubernetes Manifests

# This workflow gets triggered whenever Docker Hub sends a repository_dispatch event to your GitHub repository
on:
  repository_dispatch:
    types: [docker_push]

# A workflow run is made up of one or more jobs
jobs:
  # This is the job to update the manifests
  update-manifests:
    # This job runs on the latest version of Ubuntu
    runs-on: ubuntu-latest
    steps:
    # This step checks out your repository so your job can access it
    - name: Checkout code
      uses: actions/checkout@v2

    # This step updates the Docker image tag in your Kubernetes manifests
    - name: Update Kubernetes manifests
      run: |
        sed -i "s|uj5ghare/rollouts-demo:.*|uj5ghare/rollouts-demo:${{ github.event.client_payload.tag }}|" rollout.yml

    # This step commits and pushes the changes back to your repository
    - name: Commit and push changes
      run: |
        git config --global user.name 'Uj5Ghare'
        git config --global user.email 'ujwal5ghare@gmail.com'
        git commit -am "Update Docker image tag to ${{ github.event.client_payload.tag }}"
        git push
